### ISSUE TITLE
Redmine Exception due to Hide Estimate hour

### ISSUE THREAD

**Issue by stefan-nu** [return1/redmine_hide_estimated_hours#14]
When I try to print a redmine ticket as pdf I get an Internal error.

In the redmine log I find:

```
Started GET "/issues/2949.pdf" for IP at 2017-04-13 18:50:22 +0200
Processing by IssuesController#show as PDF
  Parameters: {"id"=>"2949"}
  Current user: some_user (id=5)
  Rendered issues/show.pdf.erb (1590.5ms)
Completed 500 Internal Server Error in 1631ms (ActiveRecord: 4.0ms)

ActionView::Template::Error (undefined method `[]' for nil:NilClass):
    1: <%= raw issue_to_pdf(@issue, :journals => @journals) %>
  lib/redmine/export/pdf.rb:95:in `RDMwriteFormattedCell'
  plugins/redmine_hide_estimated_hours/lib/pdf_patch.rb:211:in `block in issue_to_pdf_with_patch'
  plugins/redmine_hide_estimated_hours/lib/pdf_patch.rb:192:in `each'
  plugins/redmine_hide_estimated_hours/lib/pdf_patch.rb:192:in `issue_to_pdf_with_patch'
  app/views/issues/show.pdf.erb:1:in `_app_views_issues_show_pdf_erb___3347497807862764003_70196387368240'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
  plugins/redmine_dmsf/lib/redmine_dmsf/webdav/no_parse.rb:33:in `call'
```

As far as I can tell, this issue is due to your plugin.
I am running the latest version of your plugin that I pulled from github commit version 991dd8940870280f02c47b62dab296747bac3194.

Could you look into this error and fix it. 

My redmine version
Environment:
  Redmine version                3.2.3.stable
  Ruby version                   1.9.3-p484 (2013-11-22) [x86_64-linux]
  Rails version                  4.2.5.2
  Environment                    production
  Database adapter               Mysql2

Please let me know if I can provide further information to help fixing the issue.

**Comment by return1** [comment]
i cannot reproduce this error on my redmine 3.2 installation, please try updating to the latest redmine and plugin version.

**Comment by stefan-nu** [comment]
I am glad to see that you are still looking for your plugin. 

I will upgrade my redmine installation including all plugins. If this error persists or reappears I'll come back to you. For the time being I consider this issue closed.
