### ISSUE TITLE
Request for adding branches for 1.4.x and 1.3.x

### ISSUE THREAD

**Issue by tarwirdur** [return1/redmine_hide_estimated_hours#17]
Perhaps it would be right to create branches:
* `redmine-1.4.x` on commit `0ada15ec9d4d965f18fe78f3dbdb6ffc8d1522f3`
* `redmine-1.3.x` on commit `0a1bf083a6026ed5e81c85efa768f10e4cf16a79`

This versions listed in changelog here: http://www.redmine.org/plugins/redmine_hide_estimated_hours

P.S. Works good with 1.4.x. Thank you!

**Comment by return1** [comment]
done, tnx!
