### ISSUE TITLE
404 error on issue edit

### ISSUE THREAD

**Issue by Bonerserk** [return1/redmine_hide_estimated_hours#23]
The plugin works great everywhere except when I try to view/edit the issues there's 404 error on the page of the issue.
ex.: https://myredminedomain.com/issue/issuenumber -> return 404

The error is thrown with every user/role, also administrator.

Downloaded from master.

- _**This is the log**_

I, [2020-03-24T14:56:17.260943 #1]  INFO -- : Completed 200 OK in 197ms (Views: 113.1ms | ActiveRecord: 43.1ms)
I, [2020-03-24T14:56:20.393200 #1]  INFO -- : Started GET "/issues/835" for 172.19.0.1 at 2020-03-24 14:56:20 +0000
I, [2020-03-24T14:56:20.394472 #1]  INFO -- : Processing by IssuesController#show as HTML
I, [2020-03-24T14:56:20.394547 #1]  INFO -- :   Parameters: {"id"=>"835"}
I, [2020-03-24T14:56:20.402390 #1]  INFO -- :   Current user: xxxx (id=6)
I, [2020-03-24T14:56:20.512864 #1]  INFO -- :   Rendering plugins/redmine_hide_estimated_hours/app/views/issues/show.html.erb within layouts/base
I, [2020-03-24T14:56:20.519348 #1]  INFO -- :   Rendered issues/_action_menu.html.erb (6.1ms)
I, [2020-03-24T14:56:20.575837 #1]  INFO -- :   Rendered plugins/redmine_agile/app/views/issues/_issue_story_points.html.erb (6.6ms)
I, [2020-03-24T14:56:20.576018 #1]  INFO -- :   Rendered plugins/redmine_agile/app/views/issues/_agile_data_labels.html.erb (6.9ms)
I, [2020-03-24T14:56:20.586220 #1]  INFO -- :   Rendered plugins/redmine_checklists/app/views/issues/_checklist.html.erb (3.5ms)
I, [2020-03-24T14:56:20.627619 #1]  INFO -- :   Rendered issue_relations/_form.html.erb (5.5ms)
I, [2020-03-24T14:56:20.629759 #1]  INFO -- :   Rendered issues/_relations.html.erb (40.1ms)
I, [2020-03-24T14:56:20.633299 #1]  INFO -- :   Rendered plugins/redmine_hide_estimated_hours/app/views/issues/show.html.erb within layouts/base (118.7ms)
W, [2020-03-24T14:56:20.633517 #1]  WARN -- : Missing template, responding with 404: Missing partial issues/_history, application/_history with {:locale=>[:it, :en], :formats=>[:html], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :rsb]}. Searched in:
   "/usr/src/redmine/plugins/redmine_hide_estimated_hours/app/views"
   "/usr/src/redmine/plugins/redmine_checklists/app/views"
   "/usr/src/redmine/plugins/redmine_agile/app/views"
   "/usr/src/redmine/plugins/plus_gantt/app/views"
   "/usr/src/redmine/plugins/easy_wbs/app/views"
   "/usr/src/redmine/plugins/easy_mindmup/app/views"
   "/usr/src/redmine/plugins/easy_gantt/app/views"
   "/usr/src/redmine/app/views"
   "/usr/local/bundle/gems/redmine_extensions-0.3.11/app/views"
   "/usr/local/bundle/gems/redmine_crm-0.0.52/app/views"
I, [2020-03-24T14:56:20.634457 #1]  INFO -- :   Rendering common/error.html.erb within layouts/base
I, [2020-03-24T14:56:20.634746 #1]  INFO -- :   Rendered common/error.html.erb within layouts/base (0.2ms)
I, [2020-03-24T14:56:20.697935 #1]  INFO -- : Completed 404 Not Found in 303ms (Views: 55.9ms | ActiveRecord: 53.9ms)

- **_This is my redmine configuration running in docker container on ubuntu virtual machine._**

1. Environment:
 * Redmine version                4.1.0.stable
 * Ruby version                   2.6.5-p114 (2019-10-01) [x86_64-linux]
 * Rails version                  5.2.4.1
 * Environment                    production
 * Database adapter               PostgreSQL
 * Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
 * Mailer delivery                smtp
2. SCM:
 * Subversion                     1.10.4
 * Mercurial                      4.8.2
 * Bazaar                         2.8.0
 * Git                            2.20.1
 * Filesystem                     
3. Redmine plugins:
 * easy_gantt                     1.12
 * easy_mindmup                   1.0
 * easy_wbs                       1.5
 * plus_gantt                     1.0.0
 * redmine_agile                  1.5.3
 * redmine_checklists             3.1.16

**_Thanks!_**

**Comment by return1** [comment]
Thanks for the report. Please use Redmine 4.0.6 until i have time to update this plugin.

**Comment by return1** [comment]
please get the latest update for this plugin 2bfcce4775ecb262fc957087694fb8a41616452b

**Comment by Bonerserk** [comment]
Thanks! works great on redmine 4.1.0.stable!
