### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by dermitdemwolf** [return1/redmine_hide_estimated_hours#24]
Hi,
thank you very much for your awesome plugin!
I just wanted to ask, if there is any chance to get the rendereing time of your plugin down.
At the moment it looks like this:

```
Rendered plugins/redmine_hide_estimated_hours/app/views/issues/index.html.erb within layouts/base (1394.1ms)
Rendered plugins/redmine_hide_estimated_hours/app/views/issues/_attributes.html.erb (140.7ms)
```
So these two processes take 2/3 of the whole loading time.
Therefor it would be nice to get that down.

We are working on this redmine instance:

```
Environment:
  Redmine version                4.0.4.stable
  Ruby version                   2.5.5-p157 (2019-03-15) [x86_64-linux]
  Rails version                  5.2.3
  redmine_hide_estimated_hours   1.0.9
```
Thank you very much!

**Comment by return1** [comment]
hi, have you tried running without the plugin? please check the rendering performance for the mentioned views. any difference?

**Comment by dermitdemwolf** [comment]
hi, you are right, there is no change in the rendering times of the elements. It's just not going through your plugin...Sorry for bothering you. Please feel free to close this non-issue. (Maybe you have a clue to improve the speed of this elements? :-) )

**Comment by return1** [comment]
no sorry, i am running a redmine installation on a AWS t3.small instance without any issues.
