### ISSUE TITLE
error on redmine 3.3

### ISSUE THREAD

**Issue by pborri** [return1/redmine_hide_estimated_hours#25]
hi after install on redmine 3.3 we have this error, can you help me?

ActionView::Template::Error (undefined method `project_issue_form_path' for #<#<Class:0x00000007af8668>:0x007f2c92781340>):
    4: <div class="splitcontentleft">
    5: <% if @issue.safe_attribute?('status_id') && @allowed_statuses.present? %>
    6: <p><%= f.select :status_id, (@allowed_statuses.collect {|p| [p.name, p.id]}), {:required => true},
    7:                 :onchange => "updateIssueFrom('#{escape_javascript project_issue_form_path(@project, :id => @issue, :format => 'js')}')" %></p>
    8: 
    9: <% else %>
   10: <p><label><%= l(:field_status) %></label> <%= h(@issue.status.name) %></p>
  plugins/redmine_hide_estimated_hours/app/views/issues/_attributes.html.erb:7:in `block in _plugins_redmine_hide_estimated_hours_app_views_issues__attributes_html_erb___3751078550790660715_69914706333140'
  app/helpers/application_helper.rb:1058:in `labelled_fields_for'
  plugins/redmine_hide_estimated_hours/app/views/issues/_attributes.html.erb:1:in `_plugins_redmine_hide_estimated_hours_app_views_issues__attributes_html_erb___3751078550790660715_69914706333140'
  app/views/issues/_form.html.erb:42:in `block in _app_views_issues__form_html_erb___1767942668988508952_69914703937680'
  app/helpers/application_helper.rb:1058:in `labelled_fields_for'
  app/views/issues/_form.html.erb:1:in `_app_views_issues__form_html_erb___1767942668988508952_69914703937680'
  app/views/issues/_edit.html.erb:8:in `block in _app_views_issues__edit_html_erb___3818692136020643424_69914703759500'
  app/helpers/application_helper.rb:1051:in `labelled_form_for'
  app/views/issues/_edit.html.erb:1:in `_app_views_issues__edit_html_erb___3818692136020643424_69914703759500'
  plugins/redmine_hide_estimated_hours/app/views/issues/show.html.erb:134:in `_plugins_redmine_hide_estimated_hours_app_views_issues_show_html_erb___3221961296161282391_69914706345840'
  app/controllers/issues_controller.rb:122:in `block (2 levels) in show'
  app/controllers/issues_controller.rb:119:in `show'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

**Comment by return1** [comment]
please upgrade to a recent redmine version, like 3.4 oder 4.1. Version 3.3 is not supported by this plugin.

**Comment by pborri** [comment]
Hi thanks for answer.



ing. Paolo Borri
CTO e-GATE s.r.l.
Uff.: +39 0112306001<tel:+39%200112306001>
Cell.: +39 3282923887<tel:+39%203282923887>
eMail/skype for business: paolo.borri@e-gate.it<mailto:paolo.borri@e-gate.it>

Send by mobile device



-------- Messaggio originale --------
Da: Dominique Lederer <notifications@github.com>
Data: 02/05/20 11:42 (GMT+01:00)
A: return1/redmine_hide_estimated_hours <redmine_hide_estimated_hours@noreply.github.com>
Cc: "Paolo PB. Borri" <paolo.borri@e-gate.it>, Author <author@noreply.github.com>
Oggetto: Re: [return1/redmine_hide_estimated_hours] error on redmine 3.3 (#25)


please upgrade to a recent redmine version, like 3.4 oder 4.1. Version 3.3 is not supported by this plugin.

**Comment by return1** [comment]
use this branch for Redmine 3.4 https://github.com/return1/redmine_hide_estimated_hours/tree/redmine-3.4.x or the latest master branch for Redmine 4.1
