### ISSUE TITLE
Using without spent time unchecked?

### ISSUE THREAD

**Issue by leppeles** [return1/redmine_hide_estimated_hours#26]
Hi, I'm wondering if there's any solution for using this plugin, but with the View spent time leaving checked. The problem is that if I uncheck it, the users are not able to see even their own time logs on a certain project/issue, which caused confusion. So in this way we're adding a new feature for managers, while reducing usability for developers.

**Comment by return1** [comment]
This plugin is just a limited workaround to hide the estimated hours by using the "view_time_entries" permission. You would have to introduce a new permission "view_spent_time_entries" which is beyond the scope of this plugin. Someone created a (outdated) fork of this plugin: https://www.redmine.org/issues/11963#note-17

I guess you have to wait for Redmine to implement that, see https://www.redmine.org/issues/12005 and https://www.redmine.org/issues/11963

**Comment by leppeles** [comment]
Thanks for the answer. Seeing the amount of issues and the popularity of them (also: https://www.redmine.org/issues/3088 which is 11 years old opened issue) I do not really understand how it is not implemented in the core redmine. 

Anyway, I ended up creating a new estimated_hours_2 column in time_entries table, and the reporting tool (grafana) pulls that data. Not visible in redmine, but still better than hiding every time entry from users.
