### ISSUE TITLE
Redmine 5.0.2 -> cannot load query_patch 

### ISSUE THREAD

**Issue by rayzilt** [return1/redmine_hide_estimated_hours#28]
Hi,

I'm not sure if this has to do with my environment, I'm unable to load the plugin.

I'm getting the following stack trace:
![image](https://user-images.githubusercontent.com/3105311/191224198-53af7719-391c-4e8d-bd1f-8c4f0c6e060a.png)

Version information:
![image](https://user-images.githubusercontent.com/3105311/191022001-2a045cff-2702-416c-95b8-02ad0d92c8c6.png)

Any idea?

**Comment by return1** [comment]
can you please check if the small changes in #29 fix your problems?

**Comment by rayzilt** [comment]
Yes! The plugin loaded successfully now :-)
