### ISSUE TITLE
Estimated hours visible with other modules (agile)

### ISSUE THREAD

**Issue by Scale-City** [return1/redmine_hide_estimated_hours#30]
Hi,

When we use this plugin in combination with others (agile / agile backlog) which also uses estimated hours then the user that doesn't have the role 'view spent time' still sees the spent time.
Creation of a task, which is a default redmine function, is not affected.

## Configuration

- Redmine 5.x (tested with 5.0.2 & 5.0.5)
- redmine_hide_estimated_hours 5.x branch version 1.0.16
- redmine_agile 1.6.5

### Redmine 
![Selection_094](https://github.com/return1/redmine_hide_estimated_hours/assets/42180720/f200c7bc-e921-4b29-86f4-d48561507dd3)

## Roles
![image](https://github.com/return1/redmine_hide_estimated_hours/assets/42180720/7d7d4f4e-c03d-44aa-9854-5ee490ac6cd6)

### Agile

![Selection_093](https://github.com/return1/redmine_hide_estimated_hours/assets/42180720/cab15df3-f1db-41e8-8f59-ab7023bb3a35)

### Agile backlog

![Selection_091](https://github.com/return1/redmine_hide_estimated_hours/assets/42180720/1160e5b2-aea7-4d16-9c00-f30d83513f77)

**Comment by return1** [comment]
Redmine does not allow customizing visibility of core fields, like it does for custom fields. As long as this is the case, _redmine_hide_estimated_hours_ is a limited workaround and will not work with any plugin that:
a) uses estimated hours in their custom templates (you would have to patch that plugin yourself)
b) patches the same core views as this plugin (one view would override the other view) 

Please see https://github.com/return1/redmine_hide_estimated_hours#readme for more info.

**Comment by Scale-City** [comment]
Thank you for your answer.
KR
