### ISSUE TITLE
Est. time still visible in single issue view.

### ISSUE THREAD

**Issue by sznowicki** [return1/redmine_hide_estimated_hours#8]
I have a role named 'client'. After applying the plugin, estimated time is missing everywhere but the single issue view.

RM information:
Redmine version                2.5.1.stable
  Ruby version                   1.8.7-p352 (2011-06-30) [x86_64-linux]
  Rails version                  3.2.17
  Environment                    production
  Database adapter               Mysql2
SCM:
  Filesystem                     
Redmine plugins:
  redmine_agile                  1.1.2-light
  redmine_hide_estimated_hours   1.0.6
  redmine_tags                   2.1.0

**Comment by return1** [comment]
closed for no feedback, please reopen if still an issue
